import { NextResponse } from 'next/server';

// Curated list of popular MCP servers
const MCP_REGISTRY = [
  {
    id: 'filesystem',
    name: 'Filesystem',
    description: 'Read, write, and manage files and directories',
    package: '@anthropic/mcp-server-filesystem',
    command: 'npx',
    args: ['-y', '@anthropic/mcp-server-filesystem', '/'],
    category: 'core',
  },
  {
    id: 'github',
    name: 'GitHub',
    description: 'Interact with GitHub repos, issues, PRs, and more',
    package: '@anthropic/mcp-server-github',
    command: 'npx',
    args: ['-y', '@anthropic/mcp-server-github'],
    env: { GITHUB_TOKEN: '' },
    category: 'dev',
  },
  {
    id: 'postgres',
    name: 'PostgreSQL',
    description: 'Query and manage PostgreSQL databases',
    package: '@anthropic/mcp-server-postgres',
    command: 'npx',
    args: ['-y', '@anthropic/mcp-server-postgres', 'postgresql://localhost/mydb'],
    category: 'data',
  },
  {
    id: 'sqlite',
    name: 'SQLite',
    description: 'Query and manage SQLite databases',
    package: '@anthropic/mcp-server-sqlite',
    command: 'npx',
    args: ['-y', '@anthropic/mcp-server-sqlite', './database.db'],
    category: 'data',
  },
  {
    id: 'brave-search',
    name: 'Brave Search',
    description: 'Web search via Brave Search API',
    package: '@anthropic/mcp-server-brave-search',
    command: 'npx',
    args: ['-y', '@anthropic/mcp-server-brave-search'],
    env: { BRAVE_API_KEY: '' },
    category: 'web',
  },
  {
    id: 'fetch',
    name: 'Fetch',
    description: 'Fetch and read web pages and APIs',
    package: '@anthropic/mcp-server-fetch',
    command: 'npx',
    args: ['-y', '@anthropic/mcp-server-fetch'],
    category: 'web',
  },
  {
    id: 'memory',
    name: 'Memory',
    description: 'Persistent memory and knowledge graph storage',
    package: '@anthropic/mcp-server-memory',
    command: 'npx',
    args: ['-y', '@anthropic/mcp-server-memory'],
    category: 'core',
  },
  {
    id: 'slack',
    name: 'Slack',
    description: 'Send messages, read channels, manage Slack workspace',
    package: '@anthropic/mcp-server-slack',
    command: 'npx',
    args: ['-y', '@anthropic/mcp-server-slack'],
    env: { SLACK_BOT_TOKEN: '', SLACK_TEAM_ID: '' },
    category: 'comms',
  },
  {
    id: 'linear',
    name: 'Linear',
    description: 'Manage Linear issues, projects, and workflows',
    package: '@anthropic/mcp-server-linear',
    command: 'npx',
    args: ['-y', '@anthropic/mcp-server-linear'],
    env: { LINEAR_API_KEY: '' },
    category: 'project',
  },
  {
    id: 'puppeteer',
    name: 'Puppeteer',
    description: 'Browser automation and web scraping',
    package: '@anthropic/mcp-server-puppeteer',
    command: 'npx',
    args: ['-y', '@anthropic/mcp-server-puppeteer'],
    category: 'web',
  },
  {
    id: 'google-maps',
    name: 'Google Maps',
    description: 'Geocoding, directions, and place search',
    package: '@anthropic/mcp-server-google-maps',
    command: 'npx',
    args: ['-y', '@anthropic/mcp-server-google-maps'],
    env: { GOOGLE_MAPS_API_KEY: '' },
    category: 'web',
  },
  {
    id: 'sentry',
    name: 'Sentry',
    description: 'Query error tracking and performance data from Sentry',
    package: '@anthropic/mcp-server-sentry',
    command: 'npx',
    args: ['-y', '@anthropic/mcp-server-sentry'],
    env: { SENTRY_AUTH_TOKEN: '' },
    category: 'dev',
  },
];

export async function GET() {
  return NextResponse.json({ servers: MCP_REGISTRY });
}
