import type { OnMount } from '@monaco-editor/react';

export const AGENT_MATRIX_THEME = 'agent-matrix-dark';

export function defineAgentMatrixTheme(monaco: Parameters<OnMount>[1]) {
  monaco.editor.defineTheme(AGENT_MATRIX_THEME, {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '6a6a8a', fontStyle: 'italic' },
      { token: 'string', foreground: '51cf66' },
      { token: 'keyword', foreground: 'cc5de8' },
      { token: 'number', foreground: 'ff922b' },
      { token: 'type', foreground: '20c997' },
      { token: 'type.identifier', foreground: '20c997' },
      { token: 'function', foreground: '4a9eff' },
      { token: 'variable', foreground: 'e0e0e0' },
      { token: 'constant', foreground: 'ff922b' },
      { token: 'operator', foreground: 'c8c8d8' },
      { token: 'delimiter', foreground: 'c8c8d8' },
      { token: 'tag', foreground: 'cc5de8' },
      { token: 'attribute.name', foreground: '4a9eff' },
      { token: 'attribute.value', foreground: '51cf66' },
      { token: 'regexp', foreground: 'ff922b' },
    ],
    colors: {
      'editor.background': '#0e0e1a',
      'editor.foreground': '#e0e0e0',
      'editor.lineHighlightBackground': '#ffffff0a',
      'editor.selectionBackground': '#4a9eff4d',
      'editor.inactiveSelectionBackground': '#4a9eff26',
      'editorLineNumber.foreground': '#555555',
      'editorLineNumber.activeForeground': '#888888',
      'editorCursor.foreground': '#4a9eff',
      'editor.wordHighlightBackground': '#4a9eff1a',
      'editorBracketMatch.background': '#4a9eff33',
      'editorBracketMatch.border': '#4a9eff66',
      'editorIndentGuide.background': '#2a2a3a',
      'editorIndentGuide.activeBackground': '#3a3a4e',
      'editorWidget.background': '#12121e',
      'editorWidget.border': '#2a2a3a',
      'editorSuggestWidget.background': '#12121e',
      'editorSuggestWidget.border': '#2a2a3a',
      'editorSuggestWidget.selectedBackground': '#4a9eff33',
      'editorHoverWidget.background': '#12121e',
      'editorHoverWidget.border': '#2a2a3a',
      'input.background': '#0e0e1a',
      'input.border': '#2a2a3a',
      'input.foreground': '#e0e0e0',
      'scrollbar.shadow': '#00000000',
      'scrollbarSlider.background': '#ffffff15',
      'scrollbarSlider.hoverBackground': '#ffffff25',
      'scrollbarSlider.activeBackground': '#ffffff35',
      'minimap.background': '#0a0a14',
      'editorGutter.background': '#0e0e1a',
    },
  });
}
